export interface NeetCodeProblem {
  id: number;
  name: string;
  pattern: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  link: string;
}

export const PATTERNS = [
  'Arrays & Hashing',
  'Two Pointers',
  'Sliding Window',
  'Stack',
  'Binary Search',
  'Linked List',
  'Trees',
  'Tries',
  'Heap / Priority Queue',
  'Backtracking',
  'Graphs',
  'Advanced Graphs',
  '1-D DP',
  '2-D DP',
  'Greedy',
  'Intervals',
  'Math & Geometry',
  'Bit Manipulation',
] as const;

// 12-week plan mapping patterns to weeks
export const WEEK_PLAN: Record<number, string[]> = {
  1: ['Arrays & Hashing', 'Two Pointers', 'Sliding Window'],
  2: ['Stack', 'Binary Search', 'Linked List'],
  3: ['Trees'],
  4: ['Trees', 'Tries', 'Heap / Priority Queue'],
  5: ['Backtracking', 'Graphs'],
  6: ['Advanced Graphs'],
  7: ['1-D DP', '2-D DP'],
  8: ['Greedy', 'Intervals', 'Math & Geometry', 'Bit Manipulation'],
  9: ['Arrays & Hashing', 'Two Pointers', 'Sliding Window', 'Stack'], // review
  10: ['Binary Search', 'Linked List', 'Trees', 'Tries'],
  11: ['Heap / Priority Queue', 'Backtracking', 'Graphs', 'Advanced Graphs'],
  12: ['1-D DP', '2-D DP', 'Greedy', 'Intervals'],
};

// For weeks > 12, cycle through review patterns
export function getWeekPatterns(week: number): string[] {
  if (week <= 12) return WEEK_PLAN[week] || [];
  // Beyond week 12: cycle weeks 9-12 (review phase)
  const cycleWeek = ((week - 9) % 4) + 9;
  return WEEK_PLAN[cycleWeek] || [];
}

export const NEETCODE_150: NeetCodeProblem[] = [
  // Arrays & Hashing
  { id: 1, name: 'Contains Duplicate', pattern: 'Arrays & Hashing', difficulty: 'Easy', link: 'https://leetcode.com/problems/contains-duplicate/' },
  { id: 2, name: 'Valid Anagram', pattern: 'Arrays & Hashing', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-anagram/' },
  { id: 3, name: 'Two Sum', pattern: 'Arrays & Hashing', difficulty: 'Easy', link: 'https://leetcode.com/problems/two-sum/' },
  { id: 4, name: 'Group Anagrams', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/group-anagrams/' },
  { id: 5, name: 'Top K Frequent Elements', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/top-k-frequent-elements/' },
  { id: 6, name: 'Encode and Decode Strings', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/encode-and-decode-strings/' },
  { id: 7, name: 'Product of Array Except Self', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/product-of-array-except-self/' },
  { id: 8, name: 'Valid Sudoku', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/valid-sudoku/' },
  { id: 9, name: 'Longest Consecutive Sequence', pattern: 'Arrays & Hashing', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
  // Two Pointers
  { id: 10, name: 'Valid Palindrome', pattern: 'Two Pointers', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-palindrome/' },
  { id: 11, name: 'Two Sum II', pattern: 'Two Pointers', difficulty: 'Medium', link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
  { id: 12, name: '3Sum', pattern: 'Two Pointers', difficulty: 'Medium', link: 'https://leetcode.com/problems/3sum/' },
  { id: 13, name: 'Container With Most Water', pattern: 'Two Pointers', difficulty: 'Medium', link: 'https://leetcode.com/problems/container-with-most-water/' },
  { id: 14, name: 'Trapping Rain Water', pattern: 'Two Pointers', difficulty: 'Hard', link: 'https://leetcode.com/problems/trapping-rain-water/' },
  // Sliding Window
  { id: 15, name: 'Best Time to Buy and Sell Stock', pattern: 'Sliding Window', difficulty: 'Easy', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
  { id: 16, name: 'Longest Substring Without Repeating', pattern: 'Sliding Window', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
  { id: 17, name: 'Longest Repeating Character Replacement', pattern: 'Sliding Window', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
  { id: 18, name: 'Permutation in String', pattern: 'Sliding Window', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutation-in-string/' },
  { id: 19, name: 'Minimum Window Substring', pattern: 'Sliding Window', difficulty: 'Hard', link: 'https://leetcode.com/problems/minimum-window-substring/' },
  { id: 20, name: 'Sliding Window Maximum', pattern: 'Sliding Window', difficulty: 'Hard', link: 'https://leetcode.com/problems/sliding-window-maximum/' },
  // Stack
  { id: 21, name: 'Valid Parentheses', pattern: 'Stack', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-parentheses/' },
  { id: 22, name: 'Min Stack', pattern: 'Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-stack/' },
  { id: 23, name: 'Evaluate Reverse Polish Notation', pattern: 'Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
  { id: 24, name: 'Generate Parentheses', pattern: 'Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/generate-parentheses/' },
  { id: 25, name: 'Daily Temperatures', pattern: 'Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/daily-temperatures/' },
  { id: 26, name: 'Car Fleet', pattern: 'Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/car-fleet/' },
  { id: 27, name: 'Largest Rectangle in Histogram', pattern: 'Stack', difficulty: 'Hard', link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
  // Binary Search
  { id: 28, name: 'Binary Search', pattern: 'Binary Search', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-search/' },
  { id: 29, name: 'Search a 2D Matrix', pattern: 'Binary Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-a-2d-matrix/' },
  { id: 30, name: 'Koko Eating Bananas', pattern: 'Binary Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/koko-eating-bananas/' },
  { id: 31, name: 'Find Minimum in Rotated Sorted Array', pattern: 'Binary Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
  { id: 32, name: 'Search in Rotated Sorted Array', pattern: 'Binary Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
  { id: 33, name: 'Time Based Key-Value Store', pattern: 'Binary Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/time-based-key-value-store/' },
  { id: 34, name: 'Median of Two Sorted Arrays', pattern: 'Binary Search', difficulty: 'Hard', link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
  // Linked List
  { id: 35, name: 'Reverse Linked List', pattern: 'Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/reverse-linked-list/' },
  { id: 36, name: 'Merge Two Sorted Lists', pattern: 'Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
  { id: 37, name: 'Linked List Cycle', pattern: 'Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/linked-list-cycle/' },
  { id: 38, name: 'Reorder List', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/reorder-list/' },
  { id: 39, name: 'Remove Nth Node From End', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
  { id: 40, name: 'Copy List with Random Pointer', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
  { id: 41, name: 'Add Two Numbers', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/add-two-numbers/' },
  { id: 42, name: 'Find the Duplicate Number', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-the-duplicate-number/' },
  { id: 43, name: 'LRU Cache', pattern: 'Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/lru-cache/' },
  { id: 44, name: 'Merge K Sorted Lists', pattern: 'Linked List', difficulty: 'Hard', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
  { id: 45, name: 'Reverse Nodes in K-Group', pattern: 'Linked List', difficulty: 'Hard', link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },
  // Trees
  { id: 46, name: 'Invert Binary Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/invert-binary-tree/' },
  { id: 47, name: 'Maximum Depth of Binary Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
  { id: 48, name: 'Diameter of Binary Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
  { id: 49, name: 'Balanced Binary Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/balanced-binary-tree/' },
  { id: 50, name: 'Same Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/same-tree/' },
  { id: 51, name: 'Subtree of Another Tree', pattern: 'Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/subtree-of-another-tree/' },
  { id: 52, name: 'Lowest Common Ancestor of BST', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
  { id: 53, name: 'Binary Tree Level Order Traversal', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
  { id: 54, name: 'Binary Tree Right Side View', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
  { id: 55, name: 'Count Good Nodes in Binary Tree', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
  { id: 56, name: 'Validate Binary Search Tree', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/validate-binary-search-tree/' },
  { id: 57, name: 'Kth Smallest Element in a BST', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
  { id: 58, name: 'Construct Binary Tree from Preorder and Inorder', pattern: 'Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
  { id: 59, name: 'Binary Tree Maximum Path Sum', pattern: 'Trees', difficulty: 'Hard', link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
  { id: 60, name: 'Serialize and Deserialize Binary Tree', pattern: 'Trees', difficulty: 'Hard', link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
  // Tries
  { id: 61, name: 'Implement Trie', pattern: 'Tries', difficulty: 'Medium', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
  { id: 62, name: 'Design Add and Search Words', pattern: 'Tries', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
  { id: 63, name: 'Word Search II', pattern: 'Tries', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-search-ii/' },
  // Heap / Priority Queue
  { id: 64, name: 'Kth Largest Element in a Stream', pattern: 'Heap / Priority Queue', difficulty: 'Easy', link: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/' },
  { id: 65, name: 'Last Stone Weight', pattern: 'Heap / Priority Queue', difficulty: 'Easy', link: 'https://leetcode.com/problems/last-stone-weight/' },
  { id: 66, name: 'K Closest Points to Origin', pattern: 'Heap / Priority Queue', difficulty: 'Medium', link: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
  { id: 67, name: 'Kth Largest Element in an Array', pattern: 'Heap / Priority Queue', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
  { id: 68, name: 'Task Scheduler', pattern: 'Heap / Priority Queue', difficulty: 'Medium', link: 'https://leetcode.com/problems/task-scheduler/' },
  { id: 69, name: 'Design Twitter', pattern: 'Heap / Priority Queue', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-twitter/' },
  { id: 70, name: 'Find Median from Data Stream', pattern: 'Heap / Priority Queue', difficulty: 'Hard', link: 'https://leetcode.com/problems/find-median-from-data-stream/' },
  // Backtracking
  { id: 71, name: 'Subsets', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/subsets/' },
  { id: 72, name: 'Combination Sum', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/combination-sum/' },
  { id: 73, name: 'Permutations', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutations/' },
  { id: 74, name: 'Subsets II', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/subsets-ii/' },
  { id: 75, name: 'Combination Sum II', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/combination-sum-ii/' },
  { id: 76, name: 'Word Search', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-search/' },
  { id: 77, name: 'Palindrome Partitioning', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindrome-partitioning/' },
  { id: 78, name: 'Letter Combinations of a Phone Number', pattern: 'Backtracking', difficulty: 'Medium', link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
  { id: 79, name: 'N-Queens', pattern: 'Backtracking', difficulty: 'Hard', link: 'https://leetcode.com/problems/n-queens/' },
  // Graphs
  { id: 80, name: 'Number of Islands', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/number-of-islands/' },
  { id: 81, name: 'Clone Graph', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/clone-graph/' },
  { id: 82, name: 'Max Area of Island', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/max-area-of-island/' },
  { id: 83, name: 'Pacific Atlantic Water Flow', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
  { id: 84, name: 'Surrounded Regions', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/surrounded-regions/' },
  { id: 85, name: 'Rotting Oranges', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotting-oranges/' },
  { id: 86, name: 'Walls and Gates', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/walls-and-gates/' },
  { id: 87, name: 'Course Schedule', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule/' },
  { id: 88, name: 'Course Schedule II', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule-ii/' },
  { id: 89, name: 'Redundant Connection', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/redundant-connection/' },
  { id: 90, name: 'Graph Valid Tree', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/graph-valid-tree/' },
  { id: 91, name: 'Word Ladder', pattern: 'Graphs', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-ladder/' },
  // Advanced Graphs
  { id: 92, name: 'Reconstruct Itinerary', pattern: 'Advanced Graphs', difficulty: 'Hard', link: 'https://leetcode.com/problems/reconstruct-itinerary/' },
  { id: 93, name: 'Min Cost to Connect All Points', pattern: 'Advanced Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-cost-to-connect-all-points/' },
  { id: 94, name: 'Network Delay Time', pattern: 'Advanced Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/network-delay-time/' },
  { id: 95, name: 'Swim in Rising Water', pattern: 'Advanced Graphs', difficulty: 'Hard', link: 'https://leetcode.com/problems/swim-in-rising-water/' },
  { id: 96, name: 'Alien Dictionary', pattern: 'Advanced Graphs', difficulty: 'Hard', link: 'https://leetcode.com/problems/alien-dictionary/' },
  { id: 97, name: 'Cheapest Flights Within K Stops', pattern: 'Advanced Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/' },
  // 1-D DP
  { id: 98, name: 'Climbing Stairs', pattern: '1-D DP', difficulty: 'Easy', link: 'https://leetcode.com/problems/climbing-stairs/' },
  { id: 99, name: 'Min Cost Climbing Stairs', pattern: '1-D DP', difficulty: 'Easy', link: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
  { id: 100, name: 'House Robber', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber/' },
  { id: 101, name: 'House Robber II', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber-ii/' },
  { id: 102, name: 'Longest Palindromic Substring', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
  { id: 103, name: 'Palindromic Substrings', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindromic-substrings/' },
  { id: 104, name: 'Decode Ways', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/decode-ways/' },
  { id: 105, name: 'Coin Change', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/coin-change/' },
  { id: 106, name: 'Maximum Product Subarray', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximum-product-subarray/' },
  { id: 107, name: 'Word Break', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-break/' },
  { id: 108, name: 'Longest Increasing Subsequence', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
  { id: 109, name: 'Partition Equal Subset Sum', pattern: '1-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
  // 2-D DP
  { id: 110, name: 'Unique Paths', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/unique-paths/' },
  { id: 111, name: 'Longest Common Subsequence', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-common-subsequence/' },
  { id: 112, name: 'Best Time to Buy/Sell Stock with Cooldown', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/' },
  { id: 113, name: 'Coin Change II', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/coin-change-ii/' },
  { id: 114, name: 'Target Sum', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/target-sum/' },
  { id: 115, name: 'Interleaving String', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/interleaving-string/' },
  { id: 116, name: 'Longest Increasing Path in a Matrix', pattern: '2-D DP', difficulty: 'Hard', link: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/' },
  { id: 117, name: 'Distinct Subsequences', pattern: '2-D DP', difficulty: 'Hard', link: 'https://leetcode.com/problems/distinct-subsequences/' },
  { id: 118, name: 'Edit Distance', pattern: '2-D DP', difficulty: 'Medium', link: 'https://leetcode.com/problems/edit-distance/' },
  { id: 119, name: 'Burst Balloons', pattern: '2-D DP', difficulty: 'Hard', link: 'https://leetcode.com/problems/burst-balloons/' },
  { id: 120, name: 'Regular Expression Matching', pattern: '2-D DP', difficulty: 'Hard', link: 'https://leetcode.com/problems/regular-expression-matching/' },
  // Greedy
  { id: 121, name: 'Maximum Subarray', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximum-subarray/' },
  { id: 122, name: 'Jump Game', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/jump-game/' },
  { id: 123, name: 'Jump Game II', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/jump-game-ii/' },
  { id: 124, name: 'Gas Station', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/gas-station/' },
  { id: 125, name: 'Hand of Straights', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/hand-of-straights/' },
  { id: 126, name: 'Merge Triplets to Form Target', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/' },
  { id: 127, name: 'Partition Labels', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-labels/' },
  { id: 128, name: 'Valid Parenthesis String', pattern: 'Greedy', difficulty: 'Medium', link: 'https://leetcode.com/problems/valid-parenthesis-string/' },
  // Intervals
  { id: 129, name: 'Insert Interval', pattern: 'Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/insert-interval/' },
  { id: 130, name: 'Merge Intervals', pattern: 'Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/merge-intervals/' },
  { id: 131, name: 'Non-Overlapping Intervals', pattern: 'Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/non-overlapping-intervals/' },
  { id: 132, name: 'Meeting Rooms', pattern: 'Intervals', difficulty: 'Easy', link: 'https://leetcode.com/problems/meeting-rooms/' },
  { id: 133, name: 'Meeting Rooms II', pattern: 'Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/meeting-rooms-ii/' },
  { id: 134, name: 'Minimum Interval to Include Each Query', pattern: 'Intervals', difficulty: 'Hard', link: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/' },
  // Math & Geometry
  { id: 135, name: 'Rotate Image', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-image/' },
  { id: 136, name: 'Spiral Matrix', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/spiral-matrix/' },
  { id: 137, name: 'Set Matrix Zeroes', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/set-matrix-zeroes/' },
  { id: 138, name: 'Happy Number', pattern: 'Math & Geometry', difficulty: 'Easy', link: 'https://leetcode.com/problems/happy-number/' },
  { id: 139, name: 'Plus One', pattern: 'Math & Geometry', difficulty: 'Easy', link: 'https://leetcode.com/problems/plus-one/' },
  { id: 140, name: 'Pow(x, n)', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/powx-n/' },
  { id: 141, name: 'Multiply Strings', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/multiply-strings/' },
  { id: 142, name: 'Detect Squares', pattern: 'Math & Geometry', difficulty: 'Medium', link: 'https://leetcode.com/problems/detect-squares/' },
  // Bit Manipulation
  { id: 143, name: 'Single Number', pattern: 'Bit Manipulation', difficulty: 'Easy', link: 'https://leetcode.com/problems/single-number/' },
  { id: 144, name: 'Number of 1 Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', link: 'https://leetcode.com/problems/number-of-1-bits/' },
  { id: 145, name: 'Counting Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', link: 'https://leetcode.com/problems/counting-bits/' },
  { id: 146, name: 'Reverse Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', link: 'https://leetcode.com/problems/reverse-bits/' },
  { id: 147, name: 'Missing Number', pattern: 'Bit Manipulation', difficulty: 'Easy', link: 'https://leetcode.com/problems/missing-number/' },
  { id: 148, name: 'Sum of Two Integers', pattern: 'Bit Manipulation', difficulty: 'Medium', link: 'https://leetcode.com/problems/sum-of-two-integers/' },
  { id: 149, name: 'Reverse Integer', pattern: 'Bit Manipulation', difficulty: 'Medium', link: 'https://leetcode.com/problems/reverse-integer/' },
  { id: 150, name: 'Number of Connected Components', pattern: 'Graphs', difficulty: 'Medium', link: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/' },
];

export const SD_TOPICS = [
  // HLD Fundamentals
  'Scalability & Load Balancing',
  'Caching (Redis, CDN)',
  'CAP Theorem',
  'SQL vs NoSQL',
  'Sharding & Replication',
  'Message Queues',
  'Rate Limiting',
  // LLD Fundamentals
  'OOP Principles & SOLID',
  'Factory Pattern',
  'Strategy Pattern',
  'Observer Pattern',
  'Singleton & Decorator',
  'Repository Pattern',
  'UML Basics',
  // HLD Case Studies
  'Design Twitter/X',
  'Design URL Shortener',
  'Design Uber',
  'Design Netflix',
  'Design Rate Limiter',
  'Design Chat App (WhatsApp)',
  // LLD Case Studies
  'LLD: Parking Lot',
  'LLD: Elevator System',
  'LLD: Tic-Tac-Toe',
  'LLD: LRU Cache',
  'LLD: Booking System',
  'LLD: Notification System',
  // GenAI System Design
  'RAG System at Scale',
  'Content Moderation Pipeline (LLM)',
  'AI Agent Platform',
  'Transformer Architecture',
  'Embeddings & Vector Similarity',
  'Prompt Engineering Patterns',
  'Vector DBs (Pinecone/Chroma/pgvector)',
  'LangChain / LlamaIndex',
  'Fine-tuning vs RAG vs Prompting',
  'Evaluation of LLM Outputs',
  'Hallucination Mitigation',
  'Context Window Management',
  'Cost/Latency Optimization',
  'Guardrails & Safety',
];

export const PROJECT_MILESTONES = [
  'Architecture Doc',
  'Ingestion Pipeline',
  'Chunking Strategy',
  'Embeddings Integration',
  'Vector Store Setup',
  'Retrieval Pipeline',
  'Generation Pipeline',
  'Prompt Templates',
  'Evaluation Harness',
  'Agent / Tool-Use Layer',
  'Error Handling',
  'Guardrails',
  'Observability (Logging/Tracing)',
  'Docker Setup',
  'CI/CD Pipeline',
  'Monitoring',
  'Deployment (FastAPI/Streamlit)',
  'Eval Results Write-up',
];
